# 00. Pytorch Fundamentals
importing pytorch

In [1]:
import torch as torch
print(torch.__version__)

2.0.0


As well as some more important data science packages

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(pd, pd.__version__)
print(np, np.__version__)
print(plt)

<module 'pandas' from 'E:\\miniconda3\\envs\\pytorch\\lib\\site-packages\\pandas\\__init__.py'> 1.5.3
<module 'numpy' from 'E:\\miniconda3\\envs\\pytorch\\lib\\site-packages\\numpy\\__init__.py'> 1.24.2
<module 'matplotlib.pyplot' from 'E:\\miniconda3\\envs\\pytorch\\lib\\site-packages\\matplotlib\\pyplot.py'>


## Introduction to Tensors

tensors are a way to represent multidimensional numeric data

### creating a scalar tensor:

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

`torch.Tensor` and `torch.nn` are the 2 most popular torch classes

scalar attributes

In [7]:
scalar.ndim

0

A scalar has 0 dimensions, also we can use the `.item()` command to get the integer back

In [8]:
scalar.item()

7

### Vector

creating a vector

In [19]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Vector has only one dimension

In [11]:
vector.ndim

1

it may be misleading that a vector has only 1 dimension but it's actually only a 1D array

In [12]:
vector.shape

torch.Size([2])

### Matrix

In [18]:
matrix = torch.tensor([[7,8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

matrix has 2 dimensions

In [14]:
matrix.ndim

2

In [15]:
matrix[1]

tensor([ 9, 10])

It is important to inspect the shape of a matrix

In [16]:
matrix.shape

torch.Size([2, 2])

### Tensor

creating a tensor

In [20]:
tensor = torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
tensor.ndim

3

In [22]:
tensor.shape

torch.Size([1, 3, 3])

The shape corresponds to the tensor values we input - essentially a size 1 3x3 tensor 

**REMARK: usually matrices and tensors are named with uppercase (e.g. "TENSOR1")**

## Random Tensors

why random?
 - as creating tensors in tedious
 - it is the way new neural networks learn as they start with random numbers

`Start with random numbers -> look at data -> update numbers -> repeat`

create random tensor of size (3,4)

In [23]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2843, 0.3514, 0.5037, 0.6755],
        [0.4846, 0.8230, 0.4290, 0.0281],
        [0.5184, 0.6966, 0.5546, 0.6053]])

this created a tensor (matrix) with dimensions 3x4

In [24]:
random_tensor.ndim

2

It could even be multiple dimensions

In [25]:
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[0.0696, 0.4784, 0.7211, 0.6854, 0.6145, 0.0421, 0.6182, 0.1159,
          0.3075, 0.3119],
         [0.1116, 0.1333, 0.1560, 0.8897, 0.8910, 0.5160, 0.0130, 0.1500,
          0.0558, 0.7150],
         [0.6150, 0.3518, 0.2745, 0.0103, 0.5235, 0.5035, 0.7925, 0.4972,
          0.7729, 0.9885],
         [0.7981, 0.8283, 0.7818, 0.9344, 0.3178, 0.4198, 0.5537, 0.4115,
          0.8543, 0.4020],
         [0.8065, 0.2879, 0.1568, 0.7390, 0.1931, 0.0714, 0.2988, 0.1249,
          0.2662, 0.7569],
         [0.8437, 0.9377, 0.2461, 0.4457, 0.0275, 0.3849, 0.7673, 0.8203,
          0.2254, 0.0030],
         [0.0630, 0.0823, 0.5317, 0.3165, 0.4879, 0.2513, 0.8668, 0.6395,
          0.6735, 0.7667],
         [0.9995, 0.1823, 0.3986, 0.5350, 0.9500, 0.2190, 0.7553, 0.2560,
          0.3646, 0.9356],
         [0.6327, 0.8851, 0.0462, 0.1086, 0.1647, 0.2015, 0.2988, 0.4661,
          0.3271, 0.0943],
         [0.4654, 0.0990, 0.0887, 0.9542, 0.0421, 0.0982, 0.5129, 0.7596,
          0.3237,

In [26]:
random_tensor.ndim

3

Create a random tensor with similar shape to image tensor

e.g. a size a width and color channels (rgb)

In [27]:
random_image_tensor = torch.rand(size=(224,224,3)) # height width colors
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)